### ISSUE TITLE
too hard. please nurf

### ISSUE THREAD

**Issue by chris-hawley** [rookie1024/RogueClicker#2]
this leaves me as frustrated as javascript.

**Comment by ray-kast** [comment]
Thanks for the feedback!  Unfortunately, this game was designed by a bunch of imbeciles in a language **even more frustrating than JavaScript**, so there's not much that can be done about that at this point.  Hope you can enjoy the game anyway, and sorry for any inconvenience!

Thanks again,
The PR Team
